# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baac391c9c24448a1a7ac4b69a4524c70b07f9a561a327ae22dd31ba88ad1370ff12d639b77b87f40620433d4a852ae9ae3b320740c78a247424393118860d23

test:
  secret_key_base: d80020735fa3ca34e663d3007d817a1a388eec6a139fd8935cc74dcafc9e2dc3a82fc5962774a71335fcec402a6487e3100fe4238d4f69c82df6507b4a576359

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
